"""
opportunities/migrations/0001_initial.py

Generated by: django.db.migrations
"""
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Full title of the opportunity.", max_length=255)),
                ("slug", models.SlugField(blank=True, help_text="URL-safe identifier. Auto-generated from title if left blank.", max_length=280, unique=True)),
                ("reference_number", models.CharField(blank=True, help_text="e.g. IF/TDR/2026/001. Auto-generated if left blank.", max_length=50, unique=True)),
                (
                    "opportunity_type",
                    models.CharField(
                        choices=[
                            ("tender",      "Tender"),
                            ("consultancy", "Consultancy"),
                            ("job",         "Job Vacancy"),
                            ("internship",  "Internship"),
                            ("volunteer",   "Volunteer Opportunity"),
                            ("eoi",         "Expression of Interest"),
                        ],
                        db_index=True,
                        default="tender",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft",    "Draft"),
                            ("open",     "Open"),
                            ("closed",   "Closed"),
                            ("awarded",  "Awarded"),
                            ("filled",   "Filled"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("summary",     models.TextField(blank=True, help_text="Short teaser shown on listing cards (max 500 chars).", max_length=500)),
                ("description", models.TextField(blank=True, help_text="Full body content. Supports plain text or Markdown.")),
                ("location",    models.CharField(blank=True, db_index=True, help_text="e.g. 'Kilifi County' or 'Remote'.", max_length=255)),
                ("deadline",     models.DateField(blank=True, db_index=True, help_text="Application / submission deadline.", null=True)),
                ("publish_date", models.DateField(blank=True, db_index=True, help_text="Date the opportunity goes / went live.", null=True)),
                ("closing_date", models.DateField(blank=True, help_text="Administrative closing date (may differ from deadline).", null=True)),
                ("featured_image", models.ImageField(blank=True, help_text="Banner / thumbnail image.", null=True, upload_to="opportunities/images/")),
                ("is_featured",   models.BooleanField(db_index=True, default=False, help_text="Pin to the top of the listing page.")),
                ("created_at",  models.DateTimeField(auto_now_add=True)),
                ("updated_at",  models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name":        "Opportunity",
                "verbose_name_plural": "Opportunities",
                "ordering":            ["-is_featured", "-publish_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="opportunities.opportunity",
                    ),
                ),
                ("title",       models.CharField(help_text="Human-readable label, e.g. 'Tender Document' or 'Application Form'.", max_length=255)),
                ("file",        models.FileField(help_text="Accepted formats: PDF, DOCX, XLSX, PPTX, ZIP.", upload_to="opportunities/attachments/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name":        "Attachment",
                "verbose_name_plural": "Attachments",
                "ordering":            ["uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(fields=["opportunity_type", "status"], name="opp_type_status_idx"),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(fields=["deadline"], name="opp_deadline_idx"),
        ),
    ]
