# Generated by Django 6.0.6 on 2026-06-29 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='opportuniti_opportu_f05940_idx',
            old_name='opp_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='opportuniti_deadlin_294f61_idx',
            old_name='opp_deadline_idx',
        ),
    ]
