# Generated by Django 5.2.2 on 2026-04-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imarikapp', '0009_leadership'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='e.g., 5000')),
                ('suffix', models.CharField(blank=True, help_text='e.g., +, %', max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('sub_label', models.CharField(blank=True, max_length=150)),
                ('color', models.CharField(default='#ee4c05', help_text='Hex color code', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon_name', models.CharField(help_text='React icon component name, e.g., FaGraduationCap', max_length=50)),
                ('color', models.CharField(default='#ee4c05', max_length=20)),
                ('bg_color', models.CharField(default='rgba(238,76,5,.1)', max_length=30)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PillarStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(choices=[('Education', 'Education'), ('Health', 'Health'), ('Environment', 'Environment'), ('Agribusiness', 'Agribusiness'), ('Disaster Response', 'Disaster Response')], max_length=50)),
                ('number', models.CharField(help_text='e.g., 160 or 10,000+', max_length=50)),
                ('unit', models.CharField(help_text='e.g., Scholars sponsored', max_length=100)),
                ('year', models.IntegerField(default=2026, help_text='Filter stats by year')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_text', models.CharField(help_text='e.g., PDF · Published March 2025 · 32 pages', max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
