# Generated by Django 5.2.2 on 2026-04-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imarikapp', '0010_bigstat_pillar_pillarstat_report_successstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('agribusiness', 'Agribusiness'), ('environment', 'Environment'), ('disaster-response', 'Disaster Response')], max_length=50)),
                ('slug', models.SlugField(help_text="e.g., 'digital-literacy' (no spaces)", max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('icon', models.CharField(help_text='Emoji icon, e.g., 🎓', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
