# Generated by Django 5.2.2 on 2026-04-04 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imarikapp', '0011_subprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprogram',
            name='objectives_list',
            field=models.TextField(blank=True, help_text='Enter ONE objective per line. Press Enter to separate.', null=True),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='overview',
            field=models.TextField(blank=True, help_text='Full programme overview', null=True),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='partners_list',
            field=models.TextField(blank=True, help_text='Enter ONE partner per line. Press Enter to separate.', null=True),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='story_attr',
            field=models.CharField(blank=True, help_text='e.g., — Baraka Peter, Beneficiary', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='story_quote',
            field=models.TextField(blank=True, help_text='The success story quote', null=True),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='desc',
            field=models.TextField(help_text='Short description for the card'),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.CreateModel(
            name='ProgramActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('subprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='imarikapp.subprogram')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g., 160 or 97%', max_length=50)),
                ('label', models.CharField(help_text='e.g., Students Sponsored', max_length=100)),
                ('sub_label', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('subprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='imarikapp.subprogram')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
